[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 200
evm_version = 'cancun'
ffi = true
fuzz_runs = 256
fs_permissions = [
  { access = "read-write", path = "./out" },
  { access = "read", path = "./" }
]

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true

[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC_URL:-https://sepolia.base.org}"

[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY:-}" }
