cd ~/solidity-starter-day1
mkdir -p .github/workflows
cat > .github/workflows/ci.yml <<'YAML'
name: Foundry CI


on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v4
        with:
          submodules: recursive
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Build
        run: forge build

      - name: Test
        run: forge test -vvv
YAML

git add .github/workflows/ci.yml
git commit -m "ci: checkout submodules + foundry"
git push

