# Remplace complètement le workflow par une version minimale fiable
cat > .github/workflows/ci.yml <<'YAML'
name: Foundry CI

on:
  push:
    branches: [ main, ci-fix ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Sync & init submodules (safety)
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
          cache: true

      - name: Show versions
        run: |
          forge --version
          solc --version || true

      - name: Build
        run: forge build --sizes

      - name: Test
        run: forge test -vvv --gas-report
YAML

git add .github/workflows/ci.yml
git commit -m "ci: minimal Foundry CI (submodules + test)"
git push origin ci-fix

