name: Foundry CI

'on':
  push:
    branches:
      - main
      - ci-fix
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs: name: required test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Show versions
        run: forge --version

      - name: Build
        run: forge build

      - name: Test
        run: forge test -vvv --gas-report

